@LaptopApi.Api_HostAddress = http://localhost:5273

### Get All Laptops
GET {{LaptopApi.Api_HostAddress}}/api/laptops
Accept: application/json

### Get Experimental List
GET {{LaptopApi.Api_HostAddress}}/api/laptops/experimental-list
Accept: application/json