using LaptopApi.Application;
using LaptopApi.Domain;
using LaptopApi.Infrastructure;
using Microsoft.FeatureManagement;

var builder = WebApplication.CreateBuilder(args); 

//Equivaent to DJANGO INSTALLED_APPS, ASP called them Dependency registration
builder.Services.AddControllers(); //teelling ASP.NET to find any class that inherit ControllerBase and register them as API route
//Swagger used for making Doc using OpenAI, it needs EndpointsApiExplorer because it cant scan api routes on its own
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// Register Feature Management, allow us to use [FeatureGate], IFeatureManager(Parent class like Cart class in django)
builder.Services.AddFeatureManagement();

// Register Clean Architecture Dependencies
//also called dependancy injection, when Interface class get called, give it the instance of the connected argument.
builder.Services.AddScoped<ILaptopRepository, InMemoryLaptopRepository>();
builder.Services.AddScoped<ILaptopService, LaptopService>();


var app = builder.Build();

//This is equivalent to Django Middleware
if (app.Environment.IsDevelopment()) //check if the app running in development
{
    app.UseSwagger(); //This activates the Swagger generation middleware. When a request comes in for the API specification, this middleware intercepts it and dynamically generates the raw OpenAPI JSON file (usually accessible at a path like /swagger/v1/swagger.json)
    app.UseSwaggerUI(); // This spins up the interactive, user-friendly frontend web interface. It reads the raw JSON generated by UseSwagger() and renders the familiar web page where you can visually inspect your routes, view schemas, and execute API requests right from your browser
}

app.UseAuthorization();//Enables security authorization middleware in the pipeline.
app.MapControllers(); //Acts as your main urls.py router. It hooks up incoming URL requests to the matching controller action attributes ([HttpGet], [HttpPost])
//also it its only read any parent class that inherit COntrollerBase inroder to read their routes
app.Run();